import {
  attribute,
  autoGeneratedHashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { DynamoDB } from "aws-sdk";
import { IndexNames } from "../helpers/constants";

const dateMarshall = (value: Date): DynamoDB.AttributeValue =>
  ({ I: value.getTime() } as DynamoDB.AttributeValue);
const dateUnmarshall = ({ N }: DynamoDB.AttributeValue): Date | undefined =>
  N ? new Date(N) : undefined;

@table("api-orders")
export class Order {
  @autoGeneratedHashKey()
  id?: string;

  @attribute({
    indexKeyConfigurations: {
      [IndexNames.Order.mint]: "HASH",
    },
  })
  mint?: string;

  @attribute()
  treasuryMint?: string;

  @attribute()
  wallet?: string;

  @attribute()
  txHash?: string;

  @attribute()
  qty?: number;

  @attribute()
  price?: number;

  @attribute()
  side?: string;

  @attribute()
  isActive?: boolean;

  @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
  createdAt?: Date;

  @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
  updatedAt?: Date;

  static BID = "bid";
  static ASK = "ask";
}
