import {
  attribute,
  autoGeneratedHashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { DynamoDB } from "aws-sdk";

const dateMarshall = (value: Date): DynamoDB.AttributeValue =>
  ({ I: value.getTime() } as DynamoDB.AttributeValue);
const dateUnmarshall = ({ N }: DynamoDB.AttributeValue): Date | undefined =>
  N ? new Date(N) : undefined;

@table("api-sales")
export class Sale {
  @autoGeneratedHashKey()
  id?: string;

  @attribute()
  txHash?: string;

  @attribute()
  askId?: string;

  @attribute()
  bidId?: string;

  @attribute()
  isActive?: boolean;

  @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
  createdAt?: Date;

  @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
  updatedAt?: Date;
}
